
HIGHLIGHT_BLOCKS = [
    'studio_play_recording',
    'studio_run_python',
    'studio_run_traj',
    'studio_run_file',
    'app_studio_traj',

    'wait_until',
    'wait',
    'loop_break',

    'set_acceleration',
    'set_speed',
    'set_angle_speed',
    'set_angle_acceleration',

    'set_gripper',
    'gripper_mode',
    'gripper_enable',
    'gripper_position',
    'gripper_speed',
    'gripper_set',
    'gripper_set_status',
    'set_suction_cup',
    'get_suction_cup',
    'check_air_pump_state',

    'gpio_get_analog',
    'gpio_get_digital',
    'gpio_set_digital',
    'gpio_get_controller_analog',
    'gpio_get_controller_digital',
    'gpio_set_controller_digital',
    'gpio_set_controller_analog',
    'gpio_set_digital_with_xyz',
    'gpio_set_controller_digital_with_xyz',
    'gpio_set_controller_analog_with_xyz',

    'move_7',
    'move_to',
    'move_arc_to',
    'move_circle',
    'move',
    'reset',
    'sleep',
    'motion_stop',
    'motion_set_state',
    'move_joints',
    'move_joints_var',
    'move_cartesian',
    'move_cartesian_var',
    'move_tool_line',

    'set_tcp_load',
    'set_tcp_offset',
    'set_world_offset',
    'set_counter_reset',
    'set_counter_increase',

    'set_bio_gripper_init',
    'set_bio_gripper',
    'check_bio_gripper_is_catch',
    'set_robotiq_init',
    'set_robotiq_gripper',
    'check_robotiq_is_catch',

    'tool_message',
    'tool_console',
    'tool_console_with_variable',

    'event_gpio_digital',
    'event_gpio_analog',
    'event_gpio_controller_digital',
    'event_gpio_controller_analog',

    'procedures_callnoreturn',
    'procedures_callreturn',

    'variables_set',
    'math_change',
    'loop_run_forever',
    'controls_whileUntil',
    'controls_repeat_ext',
    'loop_break',
]